import { Injectable } from '@nestjs/common';
import { JoiValidationPipe } from '../../common/pipes';
import * as Joi from 'joi';
import { UserInput } from '../models';
import { UserRole } from 'generated/prisma';

/**
 * User Validation Pipe
 *
 * NOTE: Password is NOT validated here as it's auto-generated by the system
 */
@Injectable()
export class UserPipe extends JoiValidationPipe {
  public buildSchema(): Joi.Schema {
    return Joi.object<UserInput>({
      email: Joi.string().email().required().messages({
        'string.email': 'Invalid email format',
        'any.required': 'Email is required',
      }),
      fullName: Joi.string().min(2).max(255).required().messages({
        'string.min': 'Full name must be at least 2 characters',
        'string.max': 'Full name cannot exceed 255 characters',
        'any.required': 'Full name is required',
      }),
      role: Joi.string()
        .valid(...Object.values(UserRole))
        .optional()
        .default(UserRole.user),
      avatarUrl: Joi.string().uri().max(500).optional().messages({
        'string.uri': 'Avatar URL must be a valid URI',
        'string.max': 'Avatar URL cannot exceed 500 characters',
      }),
    });
  }
}
