import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { UserRole } from 'generated/prisma';

/**
 * Create User DTO
 *
 * NOTE: Password is NOT included in this DTO.
 * A secure temporary password is automatically generated by the system
 * and sent to the user's email address.
 */
export class CreateUserDTO {
  @ApiProperty({
    description: 'User email address',
    example: 'john.doe@example.com',
    format: 'email',
  })
  email: string;

  @ApiProperty({
    description: 'Full name of the user',
    example: 'John Doe',
  })
  fullName: string;

  @ApiPropertyOptional({
    description: 'User role in the system',
    enum: UserRole,
    enumName: 'UserRole',
    default: UserRole.user,
    example: UserRole.user,
  })
  role?: UserRole;

  @ApiPropertyOptional({
    description: 'URL to user avatar image',
    example: 'https://example.com/avatars/johndoe.jpg',
    format: 'uri',
  })
  avatarUrl?: string;
}
